const learnedWords = [
    ['maintain', '保つ', 'たもつ'],
    ['praise', '褒める', 'ほめる'],
    ['advise', '勧める', 'すすめる'],
    ['admit', '認める', 'みとめる'],
    ['sad', '悲しい', 'かなしい'],
    ['celebration', 'お祝', 'おいわい'],
    ['stay up all night', '徹夜する', 'てつやする', 'てつや'],
    ['ceiling', '天井', 'てんじょう'],
    ['roof', '屋根', 'やね'],
    ['shallow', '浅い', 'あさい', 'あさ'],
    ['save', '貯める', 'ためる', 'た'],
    ['shoulder', '肩', 'かた'],
    ['稻田', '田んぼ', 'たんぼ', 'た'],
    ['田地', '畑', 'はたけ'],
    ['rare', '珍しい', 'めずらしい', 'めずら'],
    ['hill, slope', '坂', 'さか'],
    ['dead end', '行き止まり', 'いきどまり', 'い ど'],
    ['lid, cap', '蓋', 'ふた'],
    ['be born', '産(生)まれる', 'うまれる', 'う'],
    ['muggy', '蒸し暑い', 'むしあつい', 'む あつ'],
    ['oversleep', '寝坊する', 'ねぼうする', 'ねぼう'],
    ['welcome, meet', '迎える', 'むかえる', 'むか'],
    ['fish tank', '水槽', 'すいそう'],
    ['suspect', '容疑者', 'ようぎしゃ'],
    ['lose', '失う', 'うしなう', 'うしな'],
    ['raise, develop', '育てる', 'そだてる', 'そだ'],
]

export const vocab = [
    ['prevent', '防ぐ', 'ふせぐ', 'ふせ'],
    ['tornado', '竜巻', 'たつまき'],
    ['cloudy', '曇り', 'くもり', 'くも'],
    ['tears', '涙', 'なみだ'],
    ['stay up late', '夜更かしする', 'よふかしする', 'よふ'],
    ['lazy', 'だらしない', 'だらしない'],
    ['fog', '霧', 'きり'],
    ['harbor', '港', 'みなと'],
    ['lake', '湖', 'みずうみ'],
    ['tidy up', '片付ける', 'かづける', 'かづ'],
    ['catch', '捕まえる', 'つかまえる', 'つか'],
    ['pretend', 'ふりをする', 'ふりをする'],
    ['be worth doing', 'やりがいを感じる', 'やりがいをかんじる', ' かん'],
    ['misunderstand', '勘違いする', 'かんちがいする', 'かんちが'],
    ['get dirty', '汚れる', 'よごれる', 'よご'],
    ['wrap, cover/engulf', '包む', 'つつむ', 'つつ'],
    ['desired, missed/nostalgic', '懐かしい', 'なつかしい', 'なつ'],
    ['catch(fish)', '釣る', 'つる', 'つ'],
    ['sunset', '夕焼け', 'ゆうやけ', 'ゆうや'],
    ['overlap, pile up', '重なる', 'かさなる', 'かさ'],
    ['turn away, chase off', '追い返す', 'おいかえす', 'お かえ'],
    ['strike, knock, beat(drum)', '叩く', 'たたく', 'たた'],
    ['complain, appeal, resort to', '訴える', 'うったえる', 'うった'],
    ['impel, drive', '切っ掛けに', 'きっかけに', 'き か'],
    ['insult, bad mouth', '悪口を言う', 'わるぐちをいう', 'わるぐち い'],
    ['stock price', '株価', 'かぶか'],
    ['stock market', '株式市場', 'かぶしきしじょう'],
    ['noise', '騒音', 'そうおん'],
    ['hiding place, refuge', '隠れ家', 'かくれが', 'かく が'],
    ['hold(arms), have(problems)', '抱える', 'かかえる', 'かか'],
    ['get sick/intoxicated', '酔う', 'よう', 'よ'],
    ['tell a secret/leak info', 'ばらす', 'ばらす'],
    ['complain', '文句を言う', 'もんくをいう', 'もんく い'],
    ['hide (oneself)', '隠れる', 'かくれる', 'かく'],
    ['electric fan', '扇風機', 'せんぷうき'],
    ['lottery', '宝くじ', 'たからくじ', 'たから'],
    ['bustling, lively', '賑やか', 'にぎやか', 'にぎ'],
    ['ratio, percentage', '割合', 'わりあい'],
    ['calm down', '落ち着く', 'おちつく', 'お つ'],
    ['melt', '溶ける', 'とける', 'と'],
    ['missing(person)', '行方不明', 'ゆくえふめい'],
    ['sled', 'そり', 'そり'],
    ['pet owner', '飼い主', 'かいぬし', 'か ぬし'],
    ['hug', '抱く', 'だく', 'だ'],
    ['protagonist', '主人公', 'しゅじんこう'],
    ['dig', '掘る', 'ほる', 'ほ'],
    ['fold, close(shop)', '畳む', 'たたむ', 'たた'],
    ['pillar', '柱', 'はしら'],
    ['wave one\'s hands', '手を振る', 'てをふる', 'て ふ'],
    ['collapse, break down', '崩れる', 'くずれる', 'くず'],
    ['swell, get excited', '盛り上がる', 'もりあがる', 'も あ'],
    ['seed', '種', 'たね'],
    ['intense', '激しい', 'はげしい', 'はげ'],
    ['rob', '奪う', 'うばう', 'うば'],
    ['driver', '運転手', 'うんてんしゅ'],
    ['spread, layout', '敷く', 'しく', 'し'],
    ['appear, express', '表す', 'あらわす', 'あらわ'],
    ['count', '数える', 'かぞえる', 'かぞ'],
    ['soft, tender', '柔らかい', 'やわらかい', 'やわ'],
    ['fine, minute', '細かい', 'こまかい', 'こま'],
    ['entrust, deposit', '預ける', 'あずける', 'あず'],
    ['depart, split up', '別れる', 'わかれる', 'わか'],
    ['fire a gun', '銃を撃つ', 'じゅうをうつ', 'じゅう う'],
    ['fall down', '転ぶ', 'ころぶ', 'ころ'],
    ['bump', 'ぶつかる', 'ぶつかる'],
    ['apologize', '謝る', 'あやまる', 'あやま'],
    ['decoration', '飾り', 'かざり', 'かざ'],
    ['temporary housing', '仮設住宅', 'かせつじゅうたく'],
    ['application', '申し込み', 'もうしこみ'],
    ['attack, strike', '襲う', 'おそう', 'おそ'],
    ['bell', '鈴', 'すず'],
    ['carry on one\'s back', '背負う', 'せおう', 'せお'],
    ['bag, satchel', '鞄', 'かばん'],
    ['burden, trouble(someone)', '迷惑をかける', 'めいわくをかける', 'めいわく'],
    ['injure, hurt', '怪我をする', 'けがをする', 'けが'],
    ['contribute', '寄付する', 'きふする', 'きふ'],
    ['wing', '翼', 'つばさ'],
    ['branch', '枝', 'えだ'],
    ['corner', '角', 'かど'],
    ['wet', '濡れる', 'ぬれる', 'ぬ'],
    ['dry', '乾く', 'かわく', 'かわ'],
    ['tease, abuse', '苛める', 'いじめる', 'いじ'],
    ['doubt, suspicion', '疑い', 'うたがい', 'うたが'],
    ['kick', '蹴る', 'ける', 'け'],
    ['steal', '盗む', 'ぬすむ'],
    ['hill', '丘', 'おか'],
    ['pile up, accumulate', '積もる', 'つもる', 'つ'],
    ['hit(by a vehicle)', '撥ねる', 'はねる', 'は'],
    ['railway crossing', '踏切', 'ふみきり'],
    ['grow, spring up', '生える', 'はえる', 'は'],
    ['mushroom', '茸', 'きのこ'],
    ['wither', '枯れる', 'かれる', 'か'],
    ['firefly', '蛍', 'ほたる'],
    ['bark', '吠える', 'ほえる', 'ほえ'],
    ['refuse, reject', '断る', 'ことわる', 'ことわ'],
    ['harassment', '嫌がらせ', 'いやがらせ', 'いや'],
    ['threaten, menace', '脅す', 'おどす', 'おど'],
    ['bump into, collid with', '打つかる', 'ぶつかる', 'ぶ'],
    ['crack, fissure', '罅', 'ひび'],
    ['shadow', '影', 'かげ'],
    ['cape(coast)', '岬', 'みさき'],
    ['each other', 'お互い', 'おたがい', ' たが'],
    ['to swear, take an oath', '誓う', 'ちかう', 'ちか'],
    ['prick, pierce', '刺さる', 'ささる', 'さ'],
    ['lick', '舐める', 'なめる', 'な'],
    ['touch', '触る', 'さわる', 'さわ'],
    ['act, play(a part)', '演じる', 'えんじる', 'えん'],
    ['sink, set(the sun)', '沈む', 'しずむ', 'しず'],
    ['grasp, clutch, grip', '握る', 'にぎる', 'にぎ'],
    ['distribute, deal(cards)', '配る', 'くばる', 'くば'],
    ['cool, chill', '冷やす', 'ひやす', 'ひ'],
    ['bank deposit transfer', '振り込む', 'ふりこむ', 'ふ こ'],
    ['twins', '双子', 'ふたご'],
    ['home town', '故郷', 'ふるさと'],
    ['trace, remains', '跡', 'あと'],
    ['wounded, injured', '傷つく', 'きずつく', 'きず'],
    ['grandchild', '孫', 'まご'],
    ['eagerly, enthusiastically', '盛んに', 'さかんに', 'さか'],
    ['brush, polish, shine', '磨く', 'みがく', 'みが'],
    ['cavity', '虫歯', 'むしば'],
    ['dealings, business', '取り引き', 'とりひき', 'と ひ'],
];