const learnedWords = [
    ['maintain', '保つ', 'たもつ'],
    ['praise', '褒める', 'ほめる'],
    ['advise', '勧める', 'すすめる'],
    ['admit', '認める', 'みとめる'],
    ['sad', '悲しい', 'かなしい'],
    ['rare', '珍しい', 'めずらしい', 'めずら'],
    ['hill, slope', '坂', 'さか'],
    ['dead end', '行き止まり', 'いきどまり', 'い ど'],
    ['lid, cap', '蓋', 'ふた'],
    ['be born', '産(生)まれる', 'うまれる', 'う'],
    ['muggy', '蒸し暑い', 'むしあつい', 'む あつ'],
    ['welcome, meet', '迎える', 'むかえる', 'むか'],
    ['fish tank', '水槽', 'すいそう'],
    ['suspect', '容疑者', 'ようぎしゃ'],
    ['lose', '失う', 'うしなう', 'うしな'],
    ['raise, develop', '育てる', 'そだてる', 'そだ'],
    ['doubt, suspicion', '疑い', 'うたがい', 'うたが'],
    ['electric fan', '扇風機', 'せんぷうき'],
    ['burden, trouble(someone)', '迷惑をかける', 'めいわくをかける', 'めいわく'],
    ['driver', '運転手', 'うんてんしゅ'],
    ['be worth doing', 'やりがいを感じる', 'やりがいをかんじる', ' かん'],
    ['stock price', '株価', 'かぶか'],
    ['stock market', '株式市場', 'かぶしきしじょう'],
    ['dig', '掘る', 'ほる', 'ほ'],
    ['turn away, chase off', '追い返す', 'おいかえす', 'お かえ'],
    ['get sick/intoxicated', '酔う', 'よう', 'よ'],
    ['seed', '種', 'たね'],
    ['application (job, insurance)', '申し込み', 'もうしこみ'],
    ['wet', '濡れる', 'ぬれる', 'ぬ'],
    ['dry', '乾く', 'かわく', 'かわ'],
    ['appear, express', '表す', 'あらわす', 'あらわ'],
    ['catch(fish)', '釣る', 'つる', 'つ'],
    ['harbor', '港', 'みなと'],
    ['lake', '湖', 'みずうみ'],
]

export const vocab = [
    ['celebration', 'お祝', 'おいわい'],
    ['ceiling', '天井', 'てんじょう'],
    ['roof', '屋根', 'やね'],
    ['shallow', '浅い', 'あさい', 'あさ'],
    ['save', '貯める', 'ためる', 'た'],
    ['shoulder', '肩', 'かた'],
    ['稻田', '田んぼ', 'たんぼ', 'た'],
    ['strike, knock, beat(drum)', '叩く', 'たたく', 'たた'],
    ['stay up all night', '徹夜する', 'てつやする', 'てつや'],
    ['oversleep', '寝坊する', 'ねぼうする', 'ねぼう'],
    ['injure, hurt (get)', '怪我をする', 'けがをする', 'けが'],
    ['pretend', 'ふりをする', 'ふりをする'],
    ['kick', '蹴る', 'ける', 'け'],
    ['prevent', '防ぐ[を, に]', 'ふせぐ', 'ふせ'],
    ['steal', '盗む', 'ぬすむ'],
    ['tornado', '竜巻', 'たつまき'],
    ['cloudy', '曇り', 'くもり', 'くも'],
    ['tears', '涙', 'なみだ'],
    ['stay up late', '夜更かしする', 'よふかしする', 'よふ'],
    ['lazy', 'だらしない', 'だらしない'],
    ['fog', '霧', 'きり'],
    ['tidy up', '片付ける[を]', 'かづける', 'かづ'],
    ['catch', '捕まえる', 'つかまえる', 'つか'],
    ['misunderstand', '勘違いする', 'かんちがいする', 'かんちが'],
    ['get dirty', '汚れる', 'よごれる', 'よご'],
    ['wrap, cover/engulf', '包む', 'つつむ', 'つつ'],
    ['desired, missed/nostalgic', '懐かしい', 'なつかしい', 'なつ'],
    ['sunset', '夕焼け', 'ゆうやけ', 'ゆうや'],
    ['overlap, pile up', '重なる', 'かさなる', 'かさ'],
    ['complain, appeal, resort to', '訴える', 'うったえる', 'うった'],
    ['impel, drive', '切っ掛けに', 'きっかけに', 'き か'],
    ['insult, bad mouth', '悪口を言う', 'わるぐちをいう', 'わるぐち い'],
    ['noise', '騒音', 'そうおん'],
    ['hiding place, refuge', '隠れ家', 'かくれが', 'かく が'],
    ['hold(arms), have(problems)', '抱える[を]', 'かかえる', 'かか'],
    ['tell a secret/leak info', 'ばらす[を]', 'ばらす'],
    ['complain', '文句を言う', 'もんくをいう', 'もんく い'],
    ['hide (oneself)', '隠れる', 'かくれる', 'かく'],
    ['lottery', '宝くじ', 'たからくじ', 'たから'],
    ['bustling, lively', '賑やか', 'にぎやか', 'にぎ'],
    ['ratio, percentage', '割合', 'わりあい'],
    ['calm down', '落ち着く', 'おちつく', 'お つ'],
    ['melt', '溶ける', 'とける', 'と'],
    ['missing(person)', '行方不明', 'ゆくえふめい'],
    ['sled', 'そり', 'そり'],
    ['pet owner', '飼い主', 'かいぬし', 'か ぬし'],
    ['hug', '抱く[を]', 'だく', 'だ'],
    ['protagonist', '主人公', 'しゅじんこう'],
    ['fold, close(shop)', '畳む[を]', 'たたむ', 'たた'],
    ['pillar', '柱', 'はしら'],
    ['wave one\'s hands', '手を振る', 'てをふる', 'て ふ'],
    ['collapse, break down', '崩れる[が]', 'くずれる', 'くず'],
    ['swell, get excited', '盛り上がる', 'もりあがる', 'も あ'],
    ['intense', '激しい', 'はげしい', 'はげ'],
    ['rob', '奪う', 'うばう', 'うば'],
    ['spread, layout', '敷く', 'しく', 'し'],
    ['count', '数える', 'かぞえる', 'かぞ'],
    ['soft, tender', '柔らかい', 'やわらかい', 'やわ'],
    ['fine, minute', '細かい', 'こまかい', 'こま'],
    ['entrust, deposit', '預ける', 'あずける', 'あず'],
    ['depart, split up', '別れる[と]', 'わかれる', 'わか'],
    ['fire a gun', '銃を撃つ', 'じゅうをうつ', 'じゅう う'],
    ['fall down', '転ぶ', 'ころぶ', 'ころ'],
    ['apologize', '謝る', 'あやまる', 'あやま'],
    ['decoration', '飾り', 'かざり', 'かざ'],
    ['temporary housing', '仮設住宅', 'かせつじゅうたく'],
    ['attack, strike', '襲う', 'おそう', 'おそ'],
    ['bell', '鈴', 'すず'],
    ['carry on one\'s back', '背負う', 'せおう', 'せお'],
    ['bag, satchel', '鞄', 'かばん'],
    ['contribute', '寄付する', 'きふする', 'きふ'],
    ['wing', '翼', 'つばさ'],
    ['branch', '枝', 'えだ'],
    ['corner', '角', 'かど'],
    ['tease, abuse', '苛める[を]', 'いじめる', 'いじ'],
    ['hill', '丘', 'おか'],
    ['pile up, accumulate', '積もる', 'つもる', 'つ'],
    ['hit(by a vehicle)', '撥ねる[に, を]', 'はねる', 'は'],
    ['railway crossing', '踏切', 'ふみきり'],
    ['grow, spring up', '生える[が]', 'はえる', 'は'],
    ['mushroom', '茸', 'きのこ'],
    ['wither', '枯れる[が]', 'かれる', 'か'],
    ['firefly', '蛍', 'ほたる'],
    ['bark', '吠える', 'ほえる', 'ほ'],
    ['refuse, reject', '断る[を]', 'ことわる', 'ことわ'],
    ['harassment', '嫌がらせ', 'いやがらせ', 'いや'],
    ['threaten, menace', '脅す[を, と]', 'おどす', 'おど'],
    ['bump into, collid with', '打つかる[に]', 'ぶつかる', 'ぶ'],
    ['crack, fissure', '罅', 'ひび'],
    ['shadow', '影', 'かげ'],
    ['cape(coast)', '岬', 'みさき'],
    ['each other', 'お互い', 'おたがい', ' たが'],
    ['to swear, take an oath', '誓う[を]', 'ちかう', 'ちか'],
    ['prick, pierce', '刺さる[に]', 'ささる', 'さ'],
    ['lick', '舐める', 'なめる', 'な'],
    ['touch', '触る[に]', 'さわる', 'さわ'],
    ['act, play(a part)', '演じる', 'えんじる', 'えん'],
    ['sink, set(the sun)', '沈む[に, が, と]', 'しずむ', 'しず'],
    ['grasp, clutch, grip', '握る[を]', 'にぎる', 'にぎ'],
    ['distribute, deal(cards)', '配る[を, が]', 'くばる', 'くば'],
    ['cool, chill', '冷やす[を]', 'ひやす', 'ひ'],
    ['bank deposit transfer', '振り込む', 'ふりこむ', 'ふ こ'],
    ['twins', '双子', 'ふたご'],
    ['home town', '故郷', 'ふるさと'],
    ['trace, remains', '跡', 'あと'],
    ['wounded, injured', '傷つく', 'きずつく', 'きず'],
    ['grandchild', '孫', 'まご'],
    ['eagerly, enthusiastically', '盛んに', 'さかんに', 'さか'],
    ['brush, polish, shine', '磨く', 'みがく', 'みが'],
    ['cavity', '虫歯', 'むしば'],
    ['dealings, business', '取り引き', 'とりひき', 'と ひ'],
    ['damp, moist', '湿る', 'しめる', 'しめ'],
    ['turn, rotate', '回す[を]', 'まわす', 'まわ'],
    ['float', '浮く[に]', 'うく', 'う'],
    ['hesitate', '躊躇う', 'ためらう', 'ためら'],
    ['slip', '滑る', 'すべる', 'すべ'],
    ['catch, grasp, grip', '掴む[を]', 'つかむ', 'つか'],
    ['poor', '貧しい', 'まずしい', 'まず'],
    ['entrust, leave to', '任せる', 'まかせる', 'まか'],
    ['injure, hurt (someone)', '傷付ける', 'きずつける', 'きずつ'],
    ['frame', '枠', 'わく'],
    ['approach, go near', '近寄る', 'ちかよる', 'ちかよ'],
    ['worried, troubled', '悩む', 'なやむ', 'なや'],
    ['ripen, mature', '熟す', 'じゅくす', 'じゅく'],
    ['pick (flowers, fruit)', '摘む', 'つむ', 'つ'],
    ['dry, air out', '干す', 'ほす', 'ほ'],
    ['launch, set off', '打ち上げる[を]', 'うちあげる', 'う あ'],
    ['go smoothly', 'うまくいく', 'うまくいく'],
    ['refund', '還付金', 'かんぷきん'],
    ['flag', '旗', 'はた'],
    ['steadily', '着々(と)', 'ちゃくちゃく', 'ちゃく'],
    ['the thing you live for', '生き甲斐', 'いきがい', 'い がい'],
    ['add (two of the same)', '足す[を]', 'たす', 'た'],
    ['smash, crush, kill(time)', '潰す[を]', 'つぶす', 'つぶ'],
    ['drink onself drunk', '酔い潰れる', 'よいつぶれる', 'よ つぶ'],
    ['rainbow', '虹', 'にじ'],
    ['sunflower', '向日葵', 'ひまわり'],
    ['breath', '息', 'いき'],
    ['ticket barrier', '改札', 'かいさつ'],
    ['burst out, spout out', '噴き出す[を, が]', 'ふきだす', 'ふ　だ'],
    ['break', '割る', 'わる', 'わ'],
    ['mow, shear, harvest', '刈る', 'かる', 'か'],
    ['replenish stock, stock up', '仕入れる', 'しいれる', 'しい'],
    ['be preoccupied with', '気を取られる', 'きをとられる', 'き　と'],
    ['tie, fasten to', '繋ぐ', 'つなぐ', 'つな'],
    ['catch fire', '火がつく', 'ひがつく', 'ひがつく'],
    ['make a noise', '騒ぐ', 'さわぐ', 'さわ'],
    ['pass, lapse(time)', '経つ', 'たつ', 'た'],
    ['cause or make a stir', '一石を投じる', 'いっせきをとうじる', 'いっせき　とう'],
    ['throw onself into something','身に投じる', 'みにとうじる', 'み とう'],
    ['front(side)', '表', 'おもて'],
    ['back(side)', '裏', 'うら'],
    ['eagle', '鷲', 'わし'],
    ['earn(money, income)', '稼ぐ', 'かせぐ', 'かせ'],
    ['go numb', '痺れる', 'しびれる', 'しび'],
    ['exceed, cross over', '超える[を]', 'こえる', 'こ'],
    ['meager, modest', '細やか', 'ささやか', 'ささ'],
    ['appeal, call out to', '呼びかける[を, に]', 'よびかける', 'よ'],
    ['far away, remote', '遥か', 'はるか', 'はる'],
    ['blow', '吹く', 'ふく', 'ふ'],
    ['width; gap, difference', '幅', 'はば'],
    ['downtown,', '繁華街', 'はんかがい'],
    ['endeavor, try', '努める', 'つとめる', 'つと'],
    ['persuasion', '説得', 'せっとく'],
    ['treasure each encounter', '一期一会', 'いちごいちえ'],
    ['rub salt in a wound', '泣きっ面に蜂', 'なきっつらにはち', 'な　つら　はち'],
    ['two blessings at once', '両手に花', 'りょうてにはな', 'りょうて　はな'],
    ['confuse, mix up', '混同[を]', 'こんどう'],
    ['deal with, cope', '対処する', 'たいしょする', 'たいしょ'],
    ['supply a lack', '欠を補う', 'けつをおぎなう', 'けつ おぎなう'],
    ['tepid, lukewarm', '温い', 'ぬるい', 'ぬる'],
    ['leak out (gas, secret)', '漏れる[が]', 'もれる', 'も'],
    ['having no knowledge of', '身に覚えのない', 'みにおぼえのない', 'み　おぼ'],
    ['ticket window', '窓口', 'まどぐち'],
    ['establish', '設ける', 'もうける', 'もう'],
    ['save time/trouble/etc', '手間が省ける', 'てまがはぶける', 'てま　ぶ'],
    ['omit, leave out, save', '省く[を]', 'はぶく', 'はぶ'],
    ['agree', '合意する', 'ごういする', 'ごうい'],
    ['aim at', '狙う[を]', 'ねらう', 'ねら'],
    ['random, unsystematic', '出鱈目', 'でたらめ'],
    ['uneven, rough', '凸凹', 'でこぼこ'],
    ['reach, get to', '達する[を, に]', 'たっする', 'たっ'],
];