let learnedWords = [
    ['maintain', '保つ', 'たもつ'],
    ['praise', '褒める', 'ほめる'],
    ['advise', '勧める', 'すすめる'],
    ['admit', '認める', 'みとめる'],
    ['sad', '悲しい', 'かなしい'],
    ['celebration', 'お祝', 'おいわい'],
    ['stay up all night', '徹夜する', 'てつやする', 'てつや'],
    ['ceiling', '天井', 'てんじょう'],
    ['roof', '屋根', 'やね'],
    ['shallow', '浅い', 'あさい', 'あさ'],
    ['save', '貯める', 'ためる', 'た'],
]

export const vocab = [
    ['prevent', '防ぐ', 'ふせぐ', 'ふせ'],
    ['tornado', '竜巻', 'たつまき'],
    ['cloudy', '曇り', 'くもり', 'くも'],
    ['tears', '涙', 'なみだ'],
    ['stay up late', '夜更かしする', 'よふかしする', 'よふ'],
    ['oversleep', '寝坊する', 'ねぼうする', 'ねぼう'],
    ['lazy', 'だらしない', 'だらしない'],
    ['fog', '霧', 'きり'],
    ['harbor', '港', 'みなと'],
    ['lake', '湖', 'みずうみ'],
    ['tidy up', '片付ける', 'かづける', 'かづ'],
    ['catch', '捕まえる', 'つかまえる', 'つか'],
    ['hill, slope', '坂', 'さか'],
    ['dead end', '行き止まり', 'いきどまり', 'い ど'],
    ['muggy', '蒸し暑い', 'むしあつい', 'む あつ'],
    ['rare', '珍しい', 'めずらしい', 'めずら'],
    ['pretend', 'ふりをする', 'ふりをする'],
    ['be born', '産(生)まれる', 'うまれる', 'う'],
    ['be worth doing', 'やりがいを感じる', 'やりがいをかんじる', ' かん'],
    ['lose', '失う', 'うしなう', 'うし'],
    ['misunderstand', '勘違いする', 'かんちがいする', 'かんちが'],
    ['get dirty', '汚れる', 'よごれる', 'よご'],
    ['wrap, cover/engulf', '包む', 'つつむ', 'つつ'],
    ['desired, missed/nostalgic', '懐かしい', 'なつかしい', 'なつ'],
    ['catch(fish)', '釣る', 'つる', 'つ'],
    ['shoulder', '肩', 'かた'],
    ['sunset', '夕焼け', 'ゆうやけ', 'ゆうや'],
    ['overlap, pile up', '重なる', 'かさなる', 'かさ'],
    ['turn away, chase off', '追い返す', 'おいかえす', 'お かえ'],
    ['strike, knock, beat(drum)', '叩く', 'たたく', 'たた'],
    ['complain, appeal, resort to', '訴える', 'うったえる', 'うった'],
    ['impel, drive', '切っ掛けに', 'きっかけに'],
    ['insult, bad mouth', '悪口を言う', 'わるぐちをいう', 'わるぐち い'],
    ['stock price', '株価', 'かぶか'],
    ['stock market', '株式市場', 'かぶしきしじょう'],
    ['noise', '騒音', 'そうおん'],
    ['hiding place, refuge', '隠れ家', 'かくれが', 'かく が'],
    ['hold(arms), have(problems)', '抱える', 'かかえる', 'かか'],
    ['lose, get rid of', '無くす', 'なくす', 'な'],
    ['get sick/intoxicated', '酔う', 'よう', 'よ'],
    ['tell a secret/leak info', 'ばらす', 'ばらす'],
    ['complain', '文句を言う', 'もんくをいう', 'もんく い'],
    ['hide (oneself)', '隠れる', 'かくれる', 'かく'],
    ['electric fan', '扇風機', 'せんぷうき'],
    ['lottery', '宝くじ', 'たからくじ', 'たから'],
    ['bustling, lively', '賑やか', 'にぎやか', 'にぎ'],
    ['ratio, percentage', '割合', 'わりあい'],
    ['calm down', '落ち着く', 'おちつく', 'お つ'],
    ['melt', '溶ける', 'とける', 'と'],
    ['missing(person)', '行方不明', 'ゆくえふめい'],
    ['sled', 'そり', 'そり'],
    ['pet owner', '飼い主', 'かいぬし', 'か ぬし'],
    ['hug', '抱く', 'だく', 'だ'],
    ['protagonist', '主人公', 'しゅじんこう'],
    ['dig', '掘る', 'ほる', 'ほ'],
    ['fold, close(shop)', '畳む', 'たたむ', 'たた'],
    ['pillar', '柱', 'はしら'],
    ['wave one\'s hands', '手を振る', 'てをふる', 'て ふ'],
    ['稻田', '田んぼ', 'たんぼ', 'た'],
    ['田地', '畑', 'はたけ'],
    ['collapse, break down', '崩れる', 'くずれる', 'くず'],
    ['swell, get excited', '盛り上がる', 'もりあがる', 'も あ'],
    ['seed', '種', 'たね'],
    ['intense', '激しい', 'はげしい', 'はげ'],
    ['rob', '奪う', 'うばう', 'うば'],
    ['driver', '運転手', 'うんてんしゅ'],
    ['spread, layout', '敷く', 'しく', 'し'],
    ['appear, express', '表す', 'あらわす', 'あらわ'],
    ['count', '数える', 'かぞえる', 'かぞ'],
    ['soft, tender', '柔らかい', 'やわらかい', 'やわ'],
    ['fine, minute', '細かい', 'こまかい', 'こま'],
    ['raise, develop', '育てる', 'そだてる', 'そだ'],
    ['entrust, deposit', '預ける', 'あずける', 'あず'],
    ['depart, split up', '別れる', 'わかれる', 'わか'],
    ['fire a gun', '銃を撃つ', 'じゅうをうつ', 'じゅう う'],
    ['suspect', '容疑者', 'ようぎしゃ'],
    ['lid, cap', '蓋', 'ふた'],
    ['fall down', '転ぶ', 'ころぶ', 'ころ'],
    ['bump', 'ぶつかる', 'ぶつかる'],
    ['apologize', '謝る', 'あやまる', 'あやま'],
    ['fish tank', '水槽', 'すいそう'],
    ['decoration', '飾り', 'かざり', 'かざ'],
    ['temporary housing', '仮設住宅', 'かせつじゅうたく'],
    ['application', '申し込み', 'もうしこみ'],
];